<?php
namespace Piggly\Tests\ValueTypes\Advanced;

use PHPUnit\Framework\TestCase;
use Piggly\ValueTypes\Advanced\SlugType;

/**
 * @coversDefaultClass \Piggly\ValueTypes\Advanced\SlugType
 */
class SlugTypeTest extends TestCase
{
	/**
	 * Assert if $value is generated as $expected.
	 *
	 * @covers ::get
	 * @covers ::__construct
	 * @dataProvider dataValues
	 * @test Expecting positive assertion.
	 * @param string $expected Expected result.
	 * @param boolean $value Value to validate
	 * @return boolean
	 */
	public function canGenerate ( string $expected, string $value )
	{ $this->assertEquals($expected, (new SlugType($value))->get()); }

	/**
	 * A list with random values to generate.
	 * Provider to canGenerate() method.
	 * - Generated by fakerphp.
	 * @return array
	 */
	public function dataValues () : array
	{
		return [
			['mi-hijo-es-un-gangster-sin-corazon-y-yo-necesito-un-abrazo',"Mi hijo es un gángster sin corazón, y yo necesito un abrazo."],
			['estaba-sentada-aqui-tomandome-algo-y-me-he-dado-cuenta-de-que-preferiria-tenerte-a-ti-en-lugar-de-la-copa',"Estaba sentada aquí tomándome algo y me he dado cuenta de que preferiría tenerte a ti en lugar de la copa."],
			['vale-puedes-quedarte-a-mi-lado-siempre-que-no-hables-sobre-la-tempertura',"Vale, puedes quedarte a mi lado, siempre que no hables sobre la tempertura."],
			['el-perro-esta-el-mejor-amigo-del-hombre',"El perro está el mejor amigo del hombre"],
			['me-encanta-vuestra-melena-rubia',"Me encanta vuestra melena rubia."],
			['da-me-los-cables-puente-de-bateria-los-pollos-se-han-escapados',"Da-me los cables puente de batería, los pollos se han escapados."],
			['tem-umas-narinas-muito-grandes-para-um-senhor-tao-pequeno',"Tem umas narinas muito grandes para um senhor tão pequeno."],
			['recuso-me-a-dormir-no-velho-castelo-assombrado-tenho-medo-de-fantasmas',"Recuso-me a dormir no velho castelo assombrado. Tenho medo de fantasmas."],
			['se-nao-queres-ir-a-loja-joao-manda-o-cao',"Se não queres ir à loja, João, manda o cão."],
			['empregado-ha-uma-criatura-horrivel-na-minha-sopa',"Empregado, há uma criatura horrível na minha sopa."],
			['a-cama-do-meu-marido-esta-cheia-de-areia-preta-porque',"A cama do meu marido está cheia de areia preta. Porquê?"],
			['se-pensa-que-vou-pagar-por-isso-esta-muito-enganado',"Se pensa que vou pagar por isso está muito enganado!"],
			['esta-foi-a-terceira-vez-esta-semana-que-um-dos-pacientes-entrou-em-combustao-espontanea',"Esta foi a terceira vez esta semana que um dos pacientes entrou em combustão espontânea."],
			['nao-confie-numa-mulher-que-tira-tudo-menos-o-chapeu',"Não confie numa mulher que tira tudo menos o chapéu."],
			['uma-vez-eu-quase-morri-de-tanta-emocao',"Uma vez eu quase morri de tanta emoção."],
			['se-eu-lhe-der-o-meu-numero-de-telefone-vai-guarda-lo-ou-deita-lo-fora',"Se eu lhe der o meu número de telefone, vai guardá-lo ou deitá-lo fora?"],
			['nao-seixe-a-sua-irma-cantar-outra-vez-nao-queremos-que-ela-parta-as-janelas-como-da-ultima-vez',"Não seixe a sua irmã cantar outra vez. Não queremos que ela parta as janelas como da última vez."],
			['j-etais-assise-avec-ma-cigarette-a-la-main-et-je-me-suis-rendu-compte-que-je-prefererais-t-avoir-toi-dans-la-main',"J'étais assise avec ma cigarette à la main et je me suis rendu compte que je préférerais t'avoir toi dans la main."],
			['d-accord-tu-peux-rester-pres-de-moi-tant-que-tu-ne-parles-pas-de-la-chaleur-qu-il-fait-ici',"D'accord, tu peux rester près de moi tant que tu ne parles pas de la chaleur qu'il fait ici."],
			['mon-fils-est-un-gangster-au-sang-froid-et-j-ai-besoin-d-un-calin',"Mon fils est un gangster au sang-froid et j'ai besoin d'un câlin."],
			['la-police-ne-t-a-pas-encore-trouve',"La police, ne t'a pas encore trouvé?"],
			['ca-te-dit-de-rentrer-chez-moi-et-de-faire-des-choses-que-je-raconterai-de-toute-facon-a-tout-le-monde',"Ça te dit de rentrer chez moi et de faire des choses que je raconterai de toute façon à tout le monde?"],
			['comme-dessert-que-me-suggereriez-vous-pour-effacer-le-gout-du-plat-de-resistance-de-ma-bouche',"Comme dessert, que me suggereriez-vous pour effacer le goût du plat de resistance de ma bouche?"],
			['je-pense-que-ce-vin-a-deja-ete-bu',"Je pense que ce vin a déjà ete bu."],
			['voulez-vous-cesser-de-me-cracher-dessus-pendant-que-vous-parlez',"Voulez-vous cesser de me cracher dessus pendant que vous parlez!"],
			['quando-ha-visto-mia-suocera-il-gatto-si-e-arrampicato-sull-albero-e-non-ne-e-ancora-sceso',"Quando ha visto mia suocera, il gatto si è arrampicato sull'albero e non ne è ancora sceso."],
			['il-mio-bicchiere-si-sente-solo-vorresti-tenergli-compagnia-con-il-tuo',"Il mio bicchiere si sente solo. Vorresti tenergli compagnia con il tuo?"],
			['se-devi-tagliarti-le-unghie-dei-piedi-vai-via-dalla-cucina-per-favore',"Se devi tagliarti le unghie dei piedi, vai via dalla cucina, per favore."],
			['che-cosa-faresti-se-ti-baciassi',"Che cosa faresti se ti baciassi?"],
			['vorresti-passare-la-notte-da-me-e-fare-tutte-quelle-cose-che-comunque-racconterei-a-tutti-che-abbiamo-fatto',"Vorresti passare la notte da me e fare tutte quelle cose che comunque racconterei a tutti che abbiamo fatto?"],
			['tre-persone-su-due-non-capiscono-le-proporzioni-in-matematica',"Tre persone su due non capiscono le proporzioni in matematica."],
			['abbiamo-visto-il-mangiatore-di-fuoco-immerso-nella-fontana',"Abbiamo visto il mangiatore di fuoco immerso nella fontana."],
			['wenn-du-nicht-selbst-in-den-laden-gehen-willst-gerald-dann-schick-doch-den-hund',"Wenn Du nicht selbst in den Laden gehen willst, Gerald, dann schick doch den Hund."],
			['mein-sohn-ist-ein-kalschnauziger-gangster-und-ich-brauche-eine-umarmung',"Mein Sohn ist ein kalschnäuziger Gangster und ich brauche eine Umarmung."],
			['trau-keiner-frau-die-alles-auszieht-nur-nicht-ihren-hut',"Trau keiner Frau, die alles auszieht - nur nicht ihren Hut!"],
			['ist-es-der-rote-oder-der-grune-knopf-der-die-bombe-entscharft',"Ist es der rote oder der grüne Knopf, der die Bombe entschärft?"],
			['keine-elephanten-in-der-bar-nach-8-uhr',"Keine Elephanten in der Bar nach 8 Uhr!"],
			['wenn-du-schon-deine-zehennagel-schneiden-musst-dann-bitte-nicht-in-der-kuche',"Wenn Du schon Deine Zehennägel schneiden musst, dann bitte nicht in der Küche!"],
			['drei-von-zwei-leuten-haben-schwierigkeiten-mit-mathematischen-verhaltnissen',"Drei von zwei Leuten haben Schwierigkeiten mit mathematischen Verhältnissen!"],
			['de-draak-blijt-volhouden-dat-we-een-meid-gaan-opofferen-anders-gaat-hij-de-hele-dorp-in-brand-steken',"De draak blijt volhouden dat we een meid gaan opofferen anders gaat hij de hele dorp in brand steken."],
			['the-dragon-insists-we-sacrifice-a-maiden-otherwise-he-will-burn-the-village-to-the-ground',"The dragon insists we sacrifice a maiden otherwise he will burn the village to the ground."],
			['on-seeing-my-mother-in-law-the-cat-ran-up-the-tree-and-hasn-t-come-down-since',"On seeing my mother-in-law, the cat ran up the tree, and hasn't come down since."],
			['three-in-two-people-do-not-understand-proportions-in-mathematics',"Three in two people do not understand proportions in mathematics."],
			['i-have-a-large-septic-boil-on-my-back-would-you-burst-it-for-me-please',"I have a large septic boil on my back. Would you burst it for me please?"],
			['we-have-seen-the-fire-eater-bathing-in-the-fountain',"We have seen the fire eater bathing in the fountain."],
			['my-son-is-a-cold-hearted-gangster-and-i-need-a-hug',"My son is a cold-hearted gangster, and I need a hug."],
			['sir-i-m-not-sure-why-the-president-was-dressed-in-women-s-clothing',"Sir, I'm not sure why the President was dressed in women's clothing."],
			['molis-eide-th-peqera-mou-h-gata-anebhke-sto-dentro-kai-den-ecei-katebei-apo-tote',"MOLIS EIDE TH PEQERA MOU, H GATA ANEBHKE STO DENTRO KAI DEN ECEI KATEBEI APO TOTE."],
			['dwse-mou-to-kapelo-sou-nomizw-oti-qa-kanw-emeto',"DWSE MOU TO KAPELO SOU - NOMIZW OTI QA KANW EMETO!"],
			['an-prepe-na-koyeis-ta-nucia-sou-edw-se-parakalw-fuge-apo-th-kouzina',"AN PREPE NA KOYEIS TA NUCIA SOU EDW, SE PARAKALW FUGE APO TH KOUZINA."],
		];
   }
}