<?php
namespace Piggly\Tests\ValueTypes\Advanced;

use PHPUnit\Framework\TestCase;
use Piggly\ValueTypes\Advanced\UnixTimestampType;

/**
 * @coversDefaultClass \Piggly\ValueTypes\Advanced\UnixTimestampType
 */
class UnixTimestampTypeTest extends TestCase
{
	/**
	 * Assert if $value is validated as $expected.
	 *
	 * @covers ::validate
	 * @covers ::assert
	 * @covers ::__construct
	 * @dataProvider dataValues
	 * @test Expecting positive assertion.
	 * @param boolean $expected Expected result.
	 * @param int $value Value to validate
	 * @return boolean
	 */
	public function canValidate ( bool $expected, int $value )
	{ $this->assertEquals($expected, (new UnixTimestampType($value))->validate()); }

	/**
	 * A list with random values to validate.
	 * Provider to canValidate() method.
	 * - Generated by fakerphp.
	 * @return array
	 */
	public function dataValues () : array
	{
		$arr = [];
		$faker = \Faker\Factory::create();

		for ( $i = 0; $i < 50; $i++ )
		{ $arr[] = [true, time()]; }

		return $arr;
   }
}