<?php
namespace Piggly\Tests\ValueTypes\Advanced;

use PHPUnit\Framework\TestCase;
use Piggly\ValueTypes\Advanced\Uuidv5Type;

/**
 * @coversDefaultClass \Piggly\ValueTypes\Advanced\Uuidv5Type
 */
class Uuidv5TypeTest extends TestCase
{
	/**
	 * Assert if $value is validated as $expected.
	 *
	 * @covers ::validate
	 * @covers ::assert
	 * @covers ::__construct
	 * @dataProvider dataValues
	 * @test Expecting positive assertion.
	 * @param boolean $expected Expected result.
	 * @param boolean $value Value to validate
	 * @return boolean
	 */
	public function canValidate ( bool $expected, string $value )
	{ $this->assertEquals($expected, (new Uuidv5Type($value))->validate()); }

	/**
	 * A list with random values to validate.
	 * Provider to canValidate() method.
	 * - Generated by fakerphp.
	 * @return array
	 */
	public function dataValues () : array
	{
		return [
			[true, 'ccf096c2-ffdd-5b93-b563-a49703f9fb8c'],
			[true, 'b3de1caf-c5a4-5ffb-9ab4-9cf1844312d6'],
			[true, '21a7c225-94fb-5eb2-8b94-8f3595f4e688'],
			[true, '7d515573-84dc-5dfe-ba81-871a75a80258'],
			[true, '08229553-e0f2-59be-b298-1e56c36845c1'],
			[true, '203f4084-bd85-5415-afa8-3082c46d8610'],
			[true, 'c4c1623b-479f-5ff1-9ca9-138489bbbd9f'],
			[true, 'ed3a57e6-358d-5778-acce-c322bc40145b'],
			[true, '2008d60b-6e7d-5fd4-91ed-11831b8a938e'],
			[true, 'bb278091-405b-53cc-9eed-2dd8987fbd2c'],
			[true, '7518f34d-f3ec-5a64-bde0-d932f46fb976'],
			[true, '25ce4f03-b0b9-56e5-b9ad-43dab4480d7b'],
			[true, '185cde1e-0308-5b69-96f6-960dec7625e3'],
			[true, '658fab7c-9b35-5e32-98f9-0d1b18b3a245'],
			[true, '565dc789-7c19-58b3-a0c8-7dcf9272623e'],
			[true, '2c1c1342-8688-55a4-a934-8e0dcea4b8b7'],
			[true, 'd563eab1-5bbc-5bb3-841e-af7f8e0dc29b'],
			[true, '93d725b0-6c30-5d64-9431-6302780f8f9f'],
			[true, '9d9470f1-c5bc-54ef-a780-157c934500a6'],
			[true, '687d0f0a-7e38-50cb-99c9-f0e473a48c2b'],
			[true, 'a01e42f1-f565-517c-aa23-1b3272e5e046'],
			[true, 'b97c5a6a-777a-51a9-a124-4c87fa1dcfae'],
			[true, '89f454d5-a017-5a26-876f-f63495a15007'],
			[true, '5494e826-33c7-584a-86b2-19b79a9b3fb7'],
			[true, '8e3cb0ba-4f32-533a-ad9c-7fb5771d6f45'],
			[true, '6d5bec96-c282-52d0-bbcc-c1c367be0bf7'],
			[true, 'c75c9c6d-55bc-5804-b7e1-53227e27f4c5'],
			[true, '347d73f2-612b-51f3-9a58-4f2102f60871'],
			[true, '7115ffeb-4558-5ae5-b879-d8db0008a75d'],
			[true, '45a5e02b-4eb7-5e93-b871-2dc02ee79c07'],
			[true, 'f7bfabdd-357c-5299-a33c-21bd7c0c8aaa'],
			[true, 'c682e688-9a3c-567a-be58-0970e6cfdb29'],
			[true, 'cef0277f-1260-56c3-b533-37ad89109fae'],
			[true, '10271b56-9321-56ba-8158-0ee9b45dc740'],
			[true, '138a0146-46cb-5d4f-94a5-77edb3592a62'],
			[true, '55589497-44fe-553c-85f0-ebf58e17f8e6'],
			[true, '526eb1bd-49f8-51ea-b9eb-a96a361dfe6e'],
			[true, '7f2aa158-879a-5680-b3c2-f3690ed99dfb'],
			[true, 'd5163977-e266-5364-962e-9d879c9590a3'],
			[true, '29a245b4-8341-555e-98b0-01479d6094fb'],
			[true, 'b8aae92d-3efe-5fc1-ab38-3f53df613ab9'],
			[true, '68441587-a9ad-526d-85a0-fe5a594da040'],
			[true, '5313f184-a709-5189-820d-dd9df051a36d'],
			[true, 'fbd59f53-58ce-5416-b446-c28d217164bd'],
			[true, 'aa16f1da-1015-55b7-8336-391963504307'],
			[true, 'eb19ebb7-9ff8-5af9-9f86-bc6c5d5ed3a2'],
			[true, 'ecc757c0-c6a4-5506-a230-6584bfa65641'],
			[true, '964829b1-099d-5740-8b97-bff1f8e287dc'],
			[true, '6ff426f7-bd7d-5522-a182-483c6414051c'],
			[true, '6db73058-00b6-5de8-acbe-950b72716bdb']
		];
   }
}