<?php
namespace Piggly\Tests\ValueTypes\Advanced;

use PHPUnit\Framework\TestCase;
use Piggly\ValueTypes\Advanced\Uuidv1Type;

/**
 * @coversDefaultClass \Piggly\ValueTypes\Advanced\Uuidv1Type
 */
class Uuidv1TypeTest extends TestCase
{
	/**
	 * Assert if $value is validated as $expected.
	 *
	 * @covers ::validate
	 * @covers ::assert
	 * @covers ::__construct
	 * @dataProvider dataValues
	 * @test Expecting positive assertion.
	 * @param boolean $expected Expected result.
	 * @param boolean $value Value to validate
	 * @return boolean
	 */
	public function canValidate ( bool $expected, string $value )
	{ $this->assertEquals($expected, (new Uuidv1Type($value))->validate()); }

	/**
	 * A list with random values to validate.
	 * Provider to canValidate() method.
	 * - Generated by fakerphp.
	 * @return array
	 */
	public function dataValues () : array
	{
		return [
			[true, '72ed3a4a-cf95-11eb-a45f-73534142ec89'],
			[true, '72ed3bda-cf95-11eb-a460-438200d0d576'],
			[true, '72ed3c16-cf95-11eb-a461-c3f67fe76027'],
			[true, '72ed3cd4-cf95-11eb-a462-afe35f3d93dc'],
			[true, '72ed3cfc-cf95-11eb-a463-67a332cc270e'],
			[true, '72ed3d2e-cf95-11eb-a464-633848e50fd1'],
			[true, '72ed3d56-cf95-11eb-a465-57f6533e4a53'],
			[true, '72ed3d7e-cf95-11eb-a466-af66f8e798d1'],
			[true, '72ed3db0-cf95-11eb-a467-0fb645a63fde'],
			[true, '72ed3dd8-cf95-11eb-a468-db857f836d10'],
			[true, '72ed3e00-cf95-11eb-a469-377a016a254a'],
			[true, '72ed3e32-cf95-11eb-a46a-23a1238e7c4e'],
			[true, '72ed3e5a-cf95-11eb-a46b-47b473820fc5'],
			[true, '72ed3e82-cf95-11eb-a46c-931050109fc1'],
			[true, '72ed3ef0-cf95-11eb-a46d-237baf906d26'],
			[true, '72ed3f22-cf95-11eb-a46e-b3bfad88e49b'],
			[true, '72ed3f86-cf95-11eb-a46f-13cfbdfc7e8f'],
			[true, '72ed3fb8-cf95-11eb-a470-238b433e6acf'],
			[true, '72ed3fe0-cf95-11eb-a471-e3d6b50f907b'],
			[true, '72ed4008-cf95-11eb-a472-6f0a8c417ee9'],
			[true, '72ed403a-cf95-11eb-a473-fbc12c739102'],
			[true, '72ed4062-cf95-11eb-a474-97dae8e8c52b'],
			[true, '72ed408a-cf95-11eb-a475-57fecfee0317'],
			[true, '72ed40b2-cf95-11eb-a476-7f1ce822b5ca'],
			[true, '72ed40e4-cf95-11eb-a477-6f21315c6cb1'],
			[true, '72ed410c-cf95-11eb-a478-5349c48b648f'],
			[true, '72ed4134-cf95-11eb-a479-9317d1ccf8d2'],
			[true, '72ed4166-cf95-11eb-a47a-13179e02e3fb'],
			[true, '72ed418e-cf95-11eb-a47b-5bf2dc81052f'],
			[true, '72ed41b6-cf95-11eb-a47c-83a2780892f1'],
			[true, '72ed41e8-cf95-11eb-a47d-33fe2a8b9e77'],
			[true, '72ed4210-cf95-11eb-a47e-ab01fc621eaf'],
			[true, '72ed4238-cf95-11eb-a47f-2be32e32b719'],
			[true, '72ed4260-cf95-11eb-a480-73c05cb16b1b'],
			[true, '72ed4292-cf95-11eb-a481-0b8d09201dc6'],
			[true, '72ed42ba-cf95-11eb-a482-17a618ff8ace'],
			[true, '72ed42e2-cf95-11eb-a483-8f28bbd88e34'],
			[true, '72ed4314-cf95-11eb-a484-8766b7d44f3a'],
			[true, '72ed433c-cf95-11eb-a485-27bfcb1570ac'],
			[true, '72ed4364-cf95-11eb-a486-938380e128eb'],
			[true, '72ed438c-cf95-11eb-a487-6b955b10d131'],
			[true, '72ed43be-cf95-11eb-a488-83e3c830cf10'],
			[true, '72ed43e6-cf95-11eb-a489-b74040273438'],
			[true, '72ed440e-cf95-11eb-a48a-731af924d708'],
			[true, '72ed4436-cf95-11eb-a48b-6784f7fe1656'],
			[true, '72ed4468-cf95-11eb-a48c-7f4995179eb9'],
			[true, '72ed4490-cf95-11eb-a48d-2bdc9ff85919'],
			[true, '72ed44b8-cf95-11eb-a48e-f7bcf76143ad'],
			[true, '72ed44ea-cf95-11eb-a48f-6f844ba1987b'],
			[true, '72ed4512-cf95-11eb-a490-7b8bfbd60400']
		];
   }
}