<?php
namespace Piggly\Tests\ValueTypes\Advanced;

use PHPUnit\Framework\TestCase;
use Piggly\ValueTypes\Advanced\Uuidv3Type;

/**
 * @coversDefaultClass \Piggly\ValueTypes\Advanced\Uuidv3Type
 */
class Uuidv3TypeTest extends TestCase
{
	/**
	 * Assert if $value is validated as $expected.
	 *
	 * @covers ::validate
	 * @covers ::assert
	 * @covers ::__construct
	 * @dataProvider dataValues
	 * @test Expecting positive assertion.
	 * @param boolean $expected Expected result.
	 * @param boolean $value Value to validate
	 * @return boolean
	 */
	public function canValidate ( bool $expected, string $value )
	{ $this->assertEquals($expected, (new Uuidv3Type($value))->validate()); }

	/**
	 * A list with random values to validate.
	 * Provider to canValidate() method.
	 * - Generated by fakerphp.
	 * @return array
	 */
	public function dataValues () : array
	{
		return [
			[true, 'b97b2921-67c3-3476-9b3c-482e151ffb2e'],
			[true, 'ab3ed29e-559d-3a82-82d1-05a407985cf3'],
			[true, '11870a99-d2d5-3b4d-ba8e-44ef95cf53c1'],
			[true, '8410cc7a-35bf-332d-989a-9c2df9a12025'],
			[true, '1656a6a0-38a9-348b-9806-d633ca21dfb3'],
			[true, '2a737442-256d-3c63-9eea-b3cf00872697'],
			[true, '7d136d50-a288-37b5-86c8-92b1574a2ac7'],
			[true, 'f02d28a6-2673-3a73-b3e0-81cddcdc1f49'],
			[true, '20c5331f-b134-3182-ad49-2ff6d984ae2a'],
			[true, '18bb84cb-5e0a-3559-86f0-29be4087f04f'],
			[true, '7570e80e-9186-37a5-ac47-8ba7ab51c997'],
			[true, '9029ed7b-844b-3116-9ca7-75d6d8f55b0f'],
			[true, 'c15c8d9b-a8f1-3d3a-8564-1bb8b37ab551'],
			[true, 'd4396f70-68d6-3850-ae47-133522acb72e'],
			[true, '6a8cb95a-c0af-3f35-8ad9-a15ec016370b'],
			[true, 'd0e23289-3781-3009-aa4b-5eeeb816fa35'],
			[true, 'f8c03fa9-412f-30e3-b965-de1da6ca5328'],
			[true, '03ff93ba-e894-3827-b7c8-1a0e1250a6e3'],
			[true, '4ec31ece-c347-30cf-8675-de75aa4da6bc'],
			[true, '6b6e9bf3-c8e1-3b09-b6d0-5f6695705087'],
			[true, '0cdff318-e871-3198-aba3-4fb9c42b9c07'],
			[true, 'e0716b75-0dc0-34a4-8b41-077b0c169966'],
			[true, '4f470eca-6d8a-3f29-af2b-413338818f85'],
			[true, 'a6f67353-f52f-3525-a733-09eb79b7397f'],
			[true, '1e272cba-15b3-392f-bf9a-6b43d19ad9c8'],
			[true, '94aa2e37-83a3-35bd-a1fc-7bba8c393ac4'],
			[true, '76e3582c-8c43-3600-a7a3-baf9cd39f407'],
			[true, '61fd43a3-8c29-3f5f-9a14-12b448019499'],
			[true, 'ed7f530a-ce3c-3889-88f1-4da55edfdfec'],
			[true, 'a209e22d-bb74-3cde-9a6a-82cf79020536'],
			[true, '6677b670-8acd-3cae-87fd-d6709901350b'],
			[true, 'ce27516f-de4f-3f7a-bc30-c7732df79de2'],
			[true, '7fd6b58c-1659-3a1b-a9d3-6c8070bc675c'],
			[true, '274a4bea-d627-34cc-9dcb-12dc1bbe21e4'],
			[true, '1932b4a2-aa6c-3cfd-b3ac-8feaa251d5ec'],
			[true, '7e8c41d7-984b-367a-9629-987bea5b602a'],
			[true, 'afb41676-956d-357c-985c-beac5bdd7e84'],
			[true, 'f78628e1-4689-3a90-a6ba-a76c1faa4621'],
			[true, 'db74f28d-e9cf-3a6d-9e82-3c0634b137b8'],
			[true, 'e01b94dd-f66b-310a-a91b-19318e7d888a'],
			[true, 'da565cb6-bfa6-3693-91d0-0c3cccf7c833'],
			[true, '31182ab3-d60a-3090-b32d-deab06949250'],
			[true, 'd3aeb07a-6c5a-3be5-b03d-08aa302b34aa'],
			[true, 'cb4b1a7e-2eeb-3cf8-be68-4ad8b4f589b3'],
			[true, 'b7676140-8be9-3563-8243-798113209f1f'],
			[true, 'fe4d4cd8-2649-3fe4-bedb-e1e909210719'],
			[true, '1835bee4-2fdc-351e-9e64-ef1b180d3bda'],
			[true, '2da2a7a9-64f6-32bf-ad0b-365ca32e4d71'],
			[true, '03390c27-9a28-30c2-9189-e022d0bf7505'],
			[true, 'd88ad963-9887-3421-87db-f4fae3437f96']
		];
   }
}